

Upgrade Upgrade_GLAExtraSalvage
  DisplayName        = UPGRADE:ExtraSalvage
  BuildTime          = 1;60.0
  BuildCost          = 0;2500
  ButtonImage        = SSExtraSalvage
  ;ResearchSound      = ScorpionTankVoiceUpgrade
End



