Upgrade Upgrade_ChinaLotusSystemHack
  DisplayName        = UPGRADE:SystemHack
  BuildTime          = 5.0
  BuildCost          = 1500
  ButtonImage        = SNLotusSystemHack
End

WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
End

;------------------------------------------------------------------------------
Object ChemicalFactory
  KindOf = +IMMUNE_TO_CAPTURE
End

;------------------------------------------------------------------------------
Object GLABurningBarrier
  KindOf = +IMMUNE_TO_CAPTURE  ;Why would this have even been capturable in the first place?
End

;------------------------------------------------------------------------------
; here, tank means container and not vehicle that destroys things
Object GLAToxinTank
  KindOf = +IMMUNE_TO_CAPTURE
End

;------------------------------------------------------------------------------
Object StanHanger02
  RemoveModule ModuleTag_03   ; nukes the GarrisonContain
End

Object CINEExplBox

  ; remove the default die
  RemoveModule ModuleTag_DIE

  AddModule  
    Behavior = InstantDeathBehavior ModuleTag_05
      FX = FX_HumveeExplosionOneFinal
    End
  End

End

AudioEvent RadarLockOnTone
  Sounds =  cloctone
  Volume = 200
  Type = ui player
End

AudioEvent AmbientWindCold
  Control = interrupt random
  Priority = high
  Volume = 110
  Sounds = awind3a awind3a
  Type = world shrouded everyone
End

AudioEvent Cin_MigFalling
  Sounds =  cmigfala
  Priority = high
  Volume = 100
  Type   = world player
End

AudioEvent Cin_SonicBoom
  Sounds =  csonicbo
  Priority = high
  Volume = 130
  Type   = ui
End

DialogEvent Cin_JetFlyOverHead
  Filename = cjetflya.wav
  Priority = high
  Volume = 100
End

AudioEvent NeutronMissileRelease
  Sounds      =  bneutlau
  Priority    = high
  Volume      = 90
  Priority    = normal
  Type        = world shrouded everyone
End

AudioEvent RadarLockOnTone
  Sounds =  cloctone
  Volume = 30
  Type = ui player
End

AudioEvent MigVoiceFalling
  Sounds = vmigfac
  Control = random
  Volume = 100
  MinVolume = 80
  Type = world shrouded player
End


