;shockwave shellmap special ini settings

;***********************Structures***********************
Object SandbagWallEnd

  RemoveModule ModuleTag_03
  RemoveModule ModuleTag_04


  KindOf = IMMOBILE CAN_SEE_THROUGH_STRUCTURE NO_COLLIDE


End

Object SandBagWall01

  RemoveModule ModuleTag_03
  RemoveModule ModuleTag_04
  
  KindOf = IMMOBILE CAN_SEE_THROUGH_STRUCTURE NO_COLLIDE

End

Object Spec_ChinaNuclearMissileLauncher

  RemoveModule ModuleTag_09

 AddModule                     ;Adds the new cannon open and close times
  
  Behavior = MissileLauncherBuildingUpdate ModuleTag_09
    SpecialPowerTemplate = SuperweaponEarthshaker
    DoorOpenTime         = 8910
    DoorWaitOpenTime     = 5000
    DoorCloseTime        = 8910

    ; FXLists to play at transitions:
    DoorOpeningFX        = TempleOFGaiaBlastDoors_Opening
    DoorOpenFX           = TempleOFGaiaBlastDoors_Opened
    DoorClosingFX        = TempleOFGaiaBlastDoors_Closing
    DoorClosedFX         = TempleOFGaiaBlastDoors_Closed
  End
  
 End

End

Object Spec_ChinaGattlingCannon

 RemoveModule ModuleTag_01     ;Removes Default art settings

AddModule                     ;Adds the new art settings
  
   Draw = W3DModelDraw ModuleTag_01

    OkToChangeModelColor = Yes

    DefaultConditionState
      Model             = NBSent_A
      Animation         = NBSent_A.NBSent_A
      AnimationMode     = MANUAL
      Turret            = TURRET01
      TurretPitch       = TURRETEL01
      WeaponFireFXBone  = PRIMARY MuzzleFX
      WeaponMuzzleFlash = PRIMARY MuzzleFX
    End
    AliasConditionState = NIGHT
    
    ConditionState      = DAMAGED
      Model             = NBSent_DA
    End
    AliasConditionState = NIGHT DAMAGED
    AliasConditionState = SNOW DAMAGED
    AliasConditionState = SNOW NIGHT DAMAGED
    
    ConditionState      = REALLYDAMAGED 
      Model             = NBSent_EA
    End
    AliasConditionState = NIGHT REALLYDAMAGED
    AliasConditionState = RUBBLE
    AliasConditionState = NIGHT RUBBLE
    AliasConditionState = SNOW REALLYDAMAGED
    AliasConditionState = SNOW NIGHT REALLYDAMAGED
    AliasConditionState = SNOW RUBBLE
    AliasConditionState = SNOW NIGHT RUBBLE 
    
    
;;;;Snow Conditionstate

    ConditionState      = SNOW
      Model             = NBSent_SA
    End
    AliasConditionState = SNOW NIGHT
    
   
    ;;Attacking States
    
;------------------------ First Spinup state ------------------------

    ConditionState      = ATTACKING
      Model             = NBSent_A
      Animation         = NBSent_A.NBSent_A
      AnimationMode     = LOOP
      AnimationSpeedFactorRange = 0.8 0.8
    End
    AliasConditionState = ATTACKING NIGHT
    
    ConditionState      = ATTACKING DAMAGED
      Model             = NBSent_DA
      Animation         = NBSent_DA.NBSent_DA
      AnimationMode     = LOOP
      AnimationSpeedFactorRange = 0.8 0.8
    End
    AliasConditionState = ATTACKING NIGHT DAMAGED
    AliasConditionState = ATTACKING SNOW DAMAGED
    AliasConditionState = ATTACKING SNOW NIGHT DAMAGED
    
    ConditionState      = ATTACKING REALLYDAMAGED 
      Model             = NBSent_EA
      Animation         = NBSent_EA.NBSent_EA
      AnimationMode     = LOOP
      AnimationSpeedFactorRange = 0.8 0.8
    End
    AliasConditionState = ATTACKING NIGHT REALLYDAMAGED
    AliasConditionState = ATTACKING RUBBLE
    AliasConditionState = ATTACKING NIGHT RUBBLE
    AliasConditionState = ATTACKING SNOW REALLYDAMAGED
    AliasConditionState = ATTACKING SNOW NIGHT REALLYDAMAGED
    AliasConditionState = ATTACKING SNOW RUBBLE
    AliasConditionState = ATTACKING SNOW NIGHT RUBBLE 
    
    
;;;;Snow Conditionstate

    ConditionState      = ATTACKING SNOW
      Model             = NBSent_SA
      Animation         = NBSent_SA.NBSent_SA
      AnimationMode     = LOOP
      AnimationSpeedFactorRange = 1.0 1.0
    End
    AliasConditionState = ATTACKING SNOW NIGHT
    
    
;------------------------ Second Spinup state ------------------------

    ConditionState      = ATTACKING CONTINUOUS_FIRE_SLOW
      Model             = NBSent_A
      Animation         = NBSent_A.NBSent_A
      AnimationMode     = LOOP
      AnimationSpeedFactorRange = 1.0 1.0
    End
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_SLOW NIGHT
    
    ConditionState      = ATTACKING CONTINUOUS_FIRE_SLOW DAMAGED
      Model             = NBSent_DA
      Animation         = NBSent_DA.NBSent_DA
      AnimationMode     = LOOP
      AnimationSpeedFactorRange = 1.0 1.0
    End
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_SLOW NIGHT DAMAGED
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_SLOW SNOW DAMAGED
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_SLOW SNOW NIGHT DAMAGED
    
    ConditionState      = ATTACKING CONTINUOUS_FIRE_SLOW REALLYDAMAGED 
      Model             = NBSent_EA
      Animation         = NBSent_EA.NBSent_EA
      AnimationMode     = LOOP
      AnimationSpeedFactorRange = 1.0 1.0
    End
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_SLOW NIGHT REALLYDAMAGED
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_SLOW RUBBLE
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_SLOW NIGHT RUBBLE
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_SLOW SNOW REALLYDAMAGED
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_SLOW SNOW NIGHT REALLYDAMAGED
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_SLOW SNOW RUBBLE
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_SLOW SNOW NIGHT RUBBLE 
    
    
;;;;Snow Conditionstate

    ConditionState      = ATTACKING CONTINUOUS_FIRE_SLOW SNOW
      Model             = NBSent_SA
      Animation         = NBSent_SA.NBSent_SA
      AnimationMode     = LOOP
      AnimationSpeedFactorRange = 1.0 1.0
    End
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_SLOW SNOW NIGHT


;------------------------ Third Spinup state ------------------------

    ConditionState      = ATTACKING CONTINUOUS_FIRE_MEAN
      Model             = NBSent_A
      Animation         = NBSent_A.NBSent_A
      AnimationMode     = LOOP
      AnimationSpeedFactorRange = 1.2 1.2
    End
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_MEAN NIGHT
    
    ConditionState      = ATTACKING CONTINUOUS_FIRE_MEAN DAMAGED
      Model             = NBSent_DA
      Animation         = NBSent_DA.NBSent_DA
      AnimationMode     = LOOP
      AnimationSpeedFactorRange = 1.2 1.2
    End
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_MEAN NIGHT DAMAGED
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_MEAN SNOW DAMAGED
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_MEAN SNOW NIGHT DAMAGED
    
    ConditionState      = ATTACKING CONTINUOUS_FIRE_MEAN REALLYDAMAGED 
      Model             = NBSent_EA
      Animation         = NBSent_EA.NBSent_EA
      AnimationMode     = LOOP
      AnimationSpeedFactorRange = 1.2 1.2
    End
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_MEAN NIGHT REALLYDAMAGED
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_MEAN RUBBLE
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_MEAN NIGHT RUBBLE
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_MEAN SNOW REALLYDAMAGED
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_MEAN SNOW NIGHT REALLYDAMAGED
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_MEAN SNOW RUBBLE
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_MEAN SNOW NIGHT RUBBLE 
    
    
;;;;Snow Conditionstate

    ConditionState      = ATTACKING CONTINUOUS_FIRE_MEAN SNOW
      Model             = NBSent_SA
      Animation         = NBSent_SA.NBSent_SA
      AnimationMode     = LOOP
      AnimationSpeedFactorRange = 1.2 1.2
    End
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_MEAN SNOW NIGHT


;------------------------ Final Spinup state ------------------------

    ConditionState      = ATTACKING CONTINUOUS_FIRE_FAST
      Model             = NBSent_A
      Animation         = NBSent_A.NBSent_A
      AnimationMode     = LOOP
      AnimationSpeedFactorRange = 1.5 1.5
      ParticleSysBone    = MuzzleFX01 GattlingMuzzleSmoke
      ParticleSysBone    = MuzzleFX02 GattlingMuzzleSmoke
    End
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_FAST NIGHT
    
    ConditionState      = ATTACKING CONTINUOUS_FIRE_FAST DAMAGED
      Model             = NBSent_DA
      Animation         = NBSent_DA.NBSent_DA
      AnimationMode     = LOOP
      AnimationSpeedFactorRange = 1.5 1.5
      ParticleSysBone    = MuzzleFX01 GattlingMuzzleSmoke
      ParticleSysBone    = MuzzleFX02 GattlingMuzzleSmoke
    End
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_FAST NIGHT DAMAGED
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_FAST SNOW DAMAGED
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_FAST SNOW NIGHT DAMAGED
    
    ConditionState      = ATTACKING CONTINUOUS_FIRE_FAST REALLYDAMAGED 
      Model             = NBSent_EA
      Animation         = NBSent_EA.NBSent_EA
      AnimationMode     = LOOP
      AnimationSpeedFactorRange = 1.5 1.5
      ParticleSysBone    = MuzzleFX01 GattlingMuzzleSmoke
      ParticleSysBone    = MuzzleFX02 GattlingMuzzleSmoke
    End
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_FAST NIGHT REALLYDAMAGED
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_FAST RUBBLE
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_FAST NIGHT RUBBLE
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_FAST SNOW REALLYDAMAGED
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_FAST SNOW NIGHT REALLYDAMAGED
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_FAST SNOW RUBBLE
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_FAST SNOW NIGHT RUBBLE 
    
    
;;;;Snow Conditionstate

    ConditionState      = ATTACKING CONTINUOUS_FIRE_FAST SNOW
      Model             = NBSent_SA
      Animation         = NBSent_SA.NBSent_SA
      AnimationMode     = LOOP
      AnimationSpeedFactorRange = 1.5 1.5
      ParticleSysBone    = MuzzleFX01 GattlingMuzzleSmoke
      ParticleSysBone    = MuzzleFX02 GattlingMuzzleSmoke
    End
    AliasConditionState = ATTACKING CONTINUOUS_FIRE_FAST SNOW NIGHT
    
  End
   
End
  
  AddModule
  
   Behavior = GrantUpgradeCreate ModuleTag_ShellmapUpgrade01
      UpgradeToGrant           = Upgrade_ChinaWhiteNapalm
   End
   
  End
  
End

Object Spec_ChinaRepairStation

  RemoveModule ModuleTag_FieldRepair01     ;Removes Stealth settings
  RemoveModule ModuleTag_FieldRepair02     ;Removes Stealth settings
  
End

;***********************Aircraft***********************

Object AmericaVehicleHumvee

  RemoveModule ModuleTag_01   ;Removes Default Art settings

  AddModule                     ;Adds the new Art settings
  
   Draw = W3DOverlordAircraftDraw  ModuleTag_01

    ParticlesAttachedToAnimatedBones = Yes
    OkToChangeModelColor = Yes

    DefaultConditionState
      Model = NVHelixTG_S
      Animation = NVHelixTG_S.NVHelixTG_S
      AnimationMode = LOOP
      HideSubObject = Muzzle03 TurretFX03
    End

    ConditionState = MOVING
      ParticleSysBone = SMOKE01 HelixExhaust
      ParticleSysBone = SMOKE02 HelixExhaust
    End

    ConditionState = REALLYDAMAGED
      Model = NVHelixTG_S
      Animation = NVHelixTG_S.NVHelixTG_S
      AnimationMode = LOOP
    End
    ConditionState = REALLYDAMAGED MOVING
      Model = NVHelixTG_S
      Animation = NVHelixTG_S.NVHelixTG_S
      AnimationMode = LOOP
      ParticleSysBone = SMOKE01 HelixExhaust
      ParticleSysBone = SMOKE02 HelixExhaust
    End

    ConditionState = RUBBLE
      Model = NVHelixTG_S
      Animation = NVHelixTG_S.NVHelixTG_S
      AnimationMode = LOOP
    End
    ConditionState = RUBBLE MOVING
      Model = NVHelixTG_S
      Animation = NVHelixTG_S.NVHelixTG_S
      AnimationMode = LOOP
      ParticleSysBone = SMOKE01 HelixExhaust
      ParticleSysBone = SMOKE02 HelixExhaust
    End

    ConditionState = RUBBLE SPECIAL_DAMAGED
      Model = NVHelixTG_S 
    End
    
   End
   
  End
  
End


Object Salv_GLAVehicleMI8Gunship

  RemoveModule ModuleTag_03     ;Removes Default Health settings

  AddModule                     ;Adds the new Health settings

   Body = ActiveBody ModuleTag_03
    MaxHealth       = 600
    InitialHealth   = 600
   End
   
  End
  
End

;***********************Vehicles***********************

Object Spec_ChinaTankDragon

  AddModule
  
   Behavior = GrantUpgradeCreate ModuleTag_ShellmapUpgrade01
      UpgradeToGrant           = Upgrade_ChinaWhiteNapalm
   End
   
  End
  
End

Object AmericaVehicleSentryDrone

  RemoveModule ModuleTag_04     ;Removes Default AIUpdate settings
  RemoveModule ModuleTag_06     ;Removes Stealth settings

  AddModule                     ;Adds the new AIUpdate settings
  
    Behavior = AIUpdateInterface ModuleTag_04
    Turret
      TurretTurnRate        = 180
      TurretPitchRate       = 180
      FirePitch             = 0            ; Instead of aiming pitchwise at the target, it will aim here
      AllowsPitch           = No
      RecenterTime          = 1000         ; how long to wait during idle before recentering
      ControlledWeaponSlots = PRIMARY TERTIARY
      NaturalTurretAngle    = 0
      InitiallyDisabled     = No
      MinIdleScanInterval   = 250    ; in milliseconds
      MaxIdleScanInterval   = 250    ; in milliseconds
      MinIdleScanAngle      = 0       ; in degrees off the natural turret angle
      MaxIdleScanAngle      = 360     ; in degrees off the natural turret angle
    End
    AutoAcquireEnemiesWhenIdle = Yes
   End
   
  End
  
  AddModule
  
   Behavior = GrantUpgradeCreate ModuleTag_ShellmapUpgrade01
      UpgradeToGrant           = Upgrade_AmericaSentryDroneGun
   End
   
  End
  
    
  AddModule
  
   Behavior = GrantUpgradeCreate ModuleTag_ShellmapUpgrade01
      UpgradeToGrant           = Upgrade_MammothRocketPods
   End
   
  End
  
End

;----------------------------------------------------------------------------------------------------------------
Object Spec_ChinaVehicleListeningOutpost

  RemoveModule ModuleTag_04     ;Removes Stealth settings
  
End

;----------------------------------------------------------------------------------------------------------------
Object Armor_ArmericaVehicleHowitzer

  RemoveModule ModuleTag_04     ;Removes Default AIUpdate settings

  AddModule                     ;Adds the new AIUpdate settings
  
    Behavior = AIUpdateInterface ModuleTag_04
        Turret
        TurretTurnRate = 100
        TurretPitchRate = 100
        AllowsPitch = Yes
        FirePitch = 25
        ControlledWeaponSlots = PRIMARY SECONDARY
      End
    AutoAcquireEnemiesWhenIdle = Yes
   End
   
  End
  
End

Object Nuke_ChinaTankBattleMaster

  RemoveModule ModuleTag_01     ;Removes Art settings
  
  AddModule                     ;Adds the new AIUpdate settings
  
   Draw = W3DOverlordTankDraw ModuleTag_01
  
    ConditionState        = NONE
      Model               = NVDeva
      Turret              = Turret01
      WeaponFireFXBone    = PRIMARY Muzzle
      WeaponRecoilBone    = PRIMARY Barrel
      WeaponMuzzleFlash   = PRIMARY MuzzleFX
      WeaponLaunchBone    = PRIMARY Muzzle
    End


    ConditionState        = REALLYDAMAGED
      Model               = NVDeva_D
      Turret              = Turret01
      WeaponFireFXBone    = PRIMARY Muzzle
      WeaponRecoilBone    = PRIMARY Barrel
      WeaponMuzzleFlash   = PRIMARY MuzzleFX
      WeaponLaunchBone    = PRIMARY Muzzle
    End


    ConditionState        = RUBBLE
      Model               = NVDeva_D
      Turret              = Turret01
      WeaponFireFXBone    = PRIMARY Muzzle
      WeaponRecoilBone    = PRIMARY Barrel
      WeaponMuzzleFlash   = PRIMARY MuzzleFX
      WeaponLaunchBone    = PRIMARY Muzzle
    End

    TrackMarks           = EXTnkTrack.tga
    OkToChangeModelColor = Yes
    MaxRecoilDistance    = 2
    TreadAnimationRate = 2.0;  amount of tread texture to move per second
    TreadDriveSpeedFraction = 0.3  ; fraction of locomotor speed below which treads stop moving.
    TreadPivotSpeedFraction = 0.6  ; fraction of locomotor speed below which we allow pivoting.
   End
   
  End
  
  WeaponSet
    Conditions = None 
    Weapon = PRIMARY   DevastatorCannonGun
  End
  
End

;----------------------------------------------------------------------------------------------------------------
Object SupW_AmericaTankShatterer

    SoundAmbient         = NoSound ;The loop stutters on the shellmap. We don't want this. Stinger. (08/09/09). 

    Locomotor            = SET_NORMAL ShattererLandLocomotor Cine_ShattererWaterLocomotor
  End

;----------------------------------------------------------------------------------------------------------------

;***********************Infantry***********************

Object GLAInfantryTunnelDefender

 AddModule                     ;Death module to prevent this unit from staying on the map forever when it doesn't get into firing range
 
  Behavior = LifetimeUpdate ModuleTag_Life01
    MinLifetime       = 30000 ;we will live for 30 seconds and then we just die
    MaxLifetime       = 30000
  End
  
 End

End

Object Salv_GLAInfantryTunnelDefender

 AddModule                     ;Death module to prevent this unit from staying on the map forever when it doesn't get into firing range
 
  Behavior = LifetimeUpdate ModuleTag_Life01
    MinLifetime       = 30000 ;we will live for 30 seconds and then we just die
    MaxLifetime       = 30000
  End
  
 End

End
Object Slth_GLAInfantryRocketSniper

  RemoveModule ModuleTag_Stealth01     ;Removes Stealth settings
  RemoveModule ModuleTag_Stealth02     ;Removes Stealth settings
  RemoveModule ModuleTag_Stealth03     ;Removes Stealth settings


 AddModule                     ;Death module to prevent this unit from staying on the map forever when it doesn't get into firing range
 
  Behavior = LifetimeUpdate ModuleTag_Life01
    MinLifetime       = 30000 ;we will live for 30 seconds and then we just die
    MaxLifetime       = 30000
  End
  
 End

End

;**********************Special Objects***********************
Object DemoSaboteurTimedCharge

  RemoveModule ModuleTag_04     ;Removes Detonation Time settings
  
  AddModule                     ;Adds New Detonation Timesettings
  
   Behavior = LifetimeUpdate ModuleTag_04
    MinLifetime = 4000   ; min lifetime in msec
    MaxLifetime = 4000   ; max lifetime in msec
   End
   
  End
  
End
