;-----------------
;AI Stuff
;-----------------

AIData

  AICrushesInfantry                   = No ; If yes, ai will attempt to crush infantry with vehicles.
End

;------------------------------------------------------------------------------
Object CINE_CarLimo3

  ReplaceModule ModuleTag_03
    Body              = ActiveBody ModuleTag_03_Override
      MaxHealth       = 150.0
      InitialHealth   = 150.0
    End
  End
  
End

Object AmericaVehicleChinook

  VisionRange         = 300.0 
  ShroudClearingRange = 350

End

;WaterTransparency
;  TransparentWaterMinOpacity = 0.75   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
;  TransparentWaterDepth = 2.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
;End

;Bridge EuropeanBridge
;  BridgeScale                    = 1.0
;  RadarColor                     = R:192 G:192 B:192
;  BridgeModelName                = CBBridgeArc
;  Texture                        = CBBridgeArc4.tga
;  BridgeModelNameDamaged         = CBBridgeArc_D
;  TextureDamaged                 = CBBridgeArc4_D.tga
;  BridgeModelNameReallyDamaged   = CBBridgeArc_E
;  TextureReallyDamaged           = CBBridgeArc4_E.tga
;  BridgeModelNameBroken          = CBBridgeArc_R
;  TextureBroken                  = CBBridgeArc4_R.tga
;  TowerObjectNameFromLeft        = EuropeanTowerBridge01
;  TowerObjectNameFromRight       = EuropeanTowerBridge01
;  TowerObjectNameToLeft          = EuropeanTowerBridge01
;  TowerObjectNameToRight         = EuropeanTowerBridge01
;  ScaffoldObjectName             = BridgeScaffold01
;  ScaffoldSupportObjectName      = BridgeScaffoldSupport01
;End

Object Dam
 ReplaceModule ModuleTag_02
  Body                = ActiveBody ModuleTag_02_Override
    MaxHealth       = 200.0
    InitialHealth   = 200.0
  End
 End
End





 

