; JDG 5/20/03 Starting Player's build list stuff here
;**********************************************************

Object AmericaInfantryColonelBurton
 Buildable = No
End

Object AmericaParticleCannonUplink
 Buildable = No
End

Object AmericaAirfield
 Buildable = No
End

Object AmericaSupplyDropZone
 Buildable = No
End


;JDG 8/6 making quonset hut non garrisonable to fix a bug
;**********************************************************
Object QuonsetHut01
  ReplaceModule ModuleTag_03
    Behavior = GarrisonContain ModuleTag_Garrison
      ContainMax          = 0
      EnterSound        = GarrisonEnter
      ExitSound         = GarrisonExit
    End
  End
End

;JDG 8/6 removing "intel" from strat center 
;**********************************************************
Object AmericaStrategyCenter
  RemoveModule SpyTag_1
End

;JDG 8/6 making radio station harder to kill
;**********************************************************
Object CivilianTEROutPost
  ReplaceModule ModuleTag_02
   Body                = StructureBody ModuleTag_HitPoint
     MaxHealth       = 5000.0
     InitialHealth   = 5000.0
   End
  END

  ReplaceModule ModuleTag_10
    Behavior = GarrisonContain ModuleTag_Garrison
      ContainMax          = 0
      EnterSound        = GarrisonEnter
      ExitSound         = GarrisonExit
    End
  End
END

;JDG 8/10 removing auto-reveal from scud storm
;**********************************************************
Object GLAScudStorm
  ShroudRevealToAllRange = 0  ; Reveals shroud to all players at a specific amount which can be different. 
                               ; Using same value? Then use KINDOF_REVEAL_TO_ALL instead!
END



  

;JDG 8/6 setting water transparancy
;**********************************************************
WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
  SkyboxTextureN = TSMoonSky_N.tga
  SkyboxTextureE = TSMoonSky_E.tga
  SkyboxTextureS = TSMoonSky_S.tga
  SkyboxTextureW = TSMoonSky_W.tga
  SkyboxTextureT = TSMoonSky_T.tga
End


;JDG 8/6 Granting upgrades here
;**********************************************************
Object AmericaBarracks
  AddModule
    Behavior = GrantUpgradeCreate ModuleTag_GLA02_give_radar
      UpgradeToGrant           = Upgrade_InfantryCaptureBuilding
    End
  End
End

Object GLABarracks
  AddModule
    Behavior = GrantUpgradeCreate ModuleTag_GLA02_give_radar
      UpgradeToGrant           = Upgrade_GLAInfantryRebelBoobyTrapAttack
    End
  End
End

