
;------------------------------------
;---------Object Overrides-----------
;------------------------------------

Object StanWatchTowerTall
 KindOf = +IMMUNE_TO_CAPTURE
End

Object StanTallTower
 KindOf = +IMMUNE_TO_CAPTURE
End

Object MogadishuTower05
 KindOf = +IMMUNE_TO_CAPTURE
End

Upgrade Upgrade_ChinaBlackNapalm
  DisplayName        = UPGRADE:BlackNapalm
  BuildTime          = 45.0
  BuildCost          = 2000
  ButtonImage        = SSBlackNapalm
  ResearchSound      = DragonTankVoiceUpgradeBlackNapalm
End

Upgrade Upgrade_ChinaChainGuns
  DisplayName        = UPGRADE:ChainGuns
  BuildTime          = 45.0
  BuildCost          = 1500
  ButtonImage        = SSGattling
  ResearchSound      = GattlingTankVoiceUpgrade
End

Upgrade Upgrade_InfantryCaptureBuilding
  DisplayName        = UPGRADE:RangerCaptureBuilding
  BuildTime          = 30.0
  BuildCost          = 1000
  ButtonImage        = SSCaptureBuilding
End

Upgrade Upgrade_ChinaLotusSystemHack
  DisplayName        = UPGRADE:SystemHack
  BuildTime          = 55.0
  BuildCost          = 1500
  ButtonImage        = SNLotusSystemHack
End


;------------------------------------------
;--------------Set Cinematics--------------
;------------------------------------------

Locomotor CINE_JarmenKellLocomotor
  Surfaces = GROUND RUBBLE
  Speed = 15                 ; was 30 in dist/sec
  SpeedDamaged = 10          ; in dist/sec
  TurnRate = 500            ; in degrees/sec
  TurnRateDamaged = 500    ; in degrees/sec
  Acceleration = 100        ; in dist/(sec^2)
  AccelerationDamaged = 50 ; in dist/(sec^2)
  Braking = 100             ; in dist/(sec^2)
  MinTurnSpeed = 0          ; in dist/sec
  ZAxisBehavior = NO_Z_MOTIVE_FORCE
  Appearance = TWO_LEGS
  StickToGround = Yes       ; walking guys aren't allowed to catch huge (or even small) air.
  GroupMovementPriority = MOVES_BACK;   Moves in the back of a group, out of danger.
End

WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
End