ModificationType: Mod
Name: Zero Hour Escalated
Version: 7.1.2
SimpleDownloadLink: https://onedrive.live.com/embed?resid=4F45B15DCCEC1DC7%217958&authkey=!AK23zfoCDKPE2b8
UIImageSourceLink: https://i.imgur.com/brs1QGw.png
DiscordLink: https://discord.com/invite/q6yh9p5ctu
ModDBLink: https://www.moddb.com/mods/zero-hour-escalated
NewsLink: https://www.moddb.com/mods/zero-hour-escalated/articles
DependenceName: ''
S3HostLink: gen.insave.ovh:9000
S3BucketName: escalatedmod
S3FolderName: escalatedmod
S3HostPublicKey: ''
S3HostSecretKey: ''
