ModificationType: Patch
Name: RotR Navy
Version: 2.0.3
SimpleDownloadLink: https://drive.usercontent.google.com/download?id=1-GGkiG9lrnZ4ykTT0u4C3t-KTGqC9_l4&export=download&authuser=0&confirm=t&uuid=a336f44a-4745-4842-b02f-a92f72f5e879&at=AENtkXYUh38A-AECBj7VEKFWUvfi%3A1732278633927
UIImageSourceLink: ''
DiscordLink: ''
ModDBLink: 'https://www.moddb.com/mods/rise-of-the-reds/addons/rise-of-the-reds-navy-20'
NewsLink: ''
DependenceName: RISE OF THE REDS
S3HostLink: ''
S3BucketName: ''
S3FolderName: ''
S3HostPublicKey: ''
S3HostSecretKey: ''
