ModificationType: Addon
Name: Shockwave Single Player Experience
Version: 2.1.3
SimpleDownloadLink: https://gen.insave.ovh/shspe/Shockwave%20Single%20Player%20Experience/Shockwave%20Single%20Player%20Experience%202.1.3.zip
UIImageSourceLink: ''
DiscordLink: ''
ModDBLink: ''
NewsLink: ''
DependenceName: C&C ShockWave
S3HostLink: gen.insave.ovh:9000
S3BucketName: shspe
S3FolderName: Shockwave Single Player Experience
S3HostPublicKey: ''
S3HostSecretKey: ''
NetworkInfo: ''

