;----------------------------------------------------------------------
Locomotor ParachuteLocomotor
  CloseEnoughDist = 10
  CloseEnoughDist3D = No   ; This allows the parachute to fly over the target and come back
End

Object GLAInfantryAngryMobPistol01
  WeaponSet
    Conditions = None 
    Weapon = PRIMARY GLAAngryMobPistolWeapon
    PreferredAgainst    = PRIMARY     INFANTRY

    Weapon = SECONDARY None

    Weapon = TERTIARY GLAAngryMobPistolWeapon
    PreferredAgainst    = TERTIARY    INFANTRY
  End
End

;------------------------------------------------------------------------------
Weapon ComancheAntiTankMissileWeapon
  ClipSize = 0              ; how many shots in a Clip (0 == infinite)
End

WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
End


