;-----------------
;AI Stuff
;-----------------

AIData

  AICrushesInfantry                   = No ; If yes, ai will attempt to crush infantry with vehicles.
End

;------------------------------------------------------------------------------
Object AmphibiousTransport
  KindOf = -SELECTABLE
End

;------------------------------------------------------------------------------
Locomotor B52Locomotor
  Speed = 150  ;80          ; in dist/sec
End

;------------------------------------------------------------------------------
Locomotor RaptorJetLocomotor
  Speed = 350; was 1500.  Everything else was 500      ; in dist/sec
  MinSpeed = 350
  Acceleration = 350         ; in dist/(sec^2)
  TurnRate = 350            ; in degrees/sec
  MinTurnSpeed = 350          ; in dist/sec
End

;------------------------------------------------------------------------------
Weapon CarpetBombWeapon
  PrimaryDamage = 1000.0            
  PrimaryDamageRadius = 1000.0      
  SecondaryDamage = 1000.0          
  SecondaryDamageRadius = 1000.0    
  AttackRange = 1000.0
End

;------------------------------------------------------------------------------
Object AmericaJetRaptor
  Buildable = No
End

;------------------------------------------------------------------------------
Object AmericaJetB52
  ReplaceModule ModuleTag_03
    Body = ActiveBody ModuleTag_03_Override
      MaxHealth       = 5200.0
      InitialHealth   = 5200.0
    End
  End
End

;------------------------------------------------------------------------------
Object CivilianBunker01
  ReplaceModule ModuleTag_02
    Body = StructureBody ModuleTag_02_Override
      MaxHealth       = 400.0
      InitialHealth   = 400.0
    End
  End
End

Object AmericaJetAurora
  Locomotor = SET_NORMAL RaptorJetLocomotor
End

Locomotor BasicAmphibiousLocomotor
  Speed = 20                ; in dist/sec
  SpeedDamaged = 15         ; in dist/sec
End

;------------------------------------------------------------------------------
Object Tent01
  ReplaceModule ModuleTag_02
    Body              = ActiveBody ModuleTag_02_Override
      MaxHealth       = 200.0
      InitialHealth   = 200.0
    End
  End
End

;------------------------------------------------------------------------------
Object Tent02
  ReplaceModule ModuleTag_02
    Body              = ActiveBody ModuleTag_02_Override
      MaxHealth       = 200.0
      InitialHealth   = 200.0
    End
  End
End

;------------------------------------------------------------------------------
Object Tent03
  ReplaceModule ModuleTag_02
    Body              = ActiveBody ModuleTag_02_Override
      MaxHealth       = 200.0
      InitialHealth   = 200.0
    End
  End
End

;------------------------------------------------------------------------------
Object Tent04
  ReplaceModule ModuleTag_02
    Body              = ActiveBody ModuleTag_02_Override
      MaxHealth       = 200.0
      InitialHealth   = 200.0
    End
  End
End

WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
End


CommandSet SpecialPowerShortcutUSA
  1 = Command_SpyDroneFromShortcut
  2 = Command_ParadropFromShortcut
  3 = Command_A10ThunderboltMissileStrikeFromShortcut
  4 = Command_EmergencyRepairFromShortcut
  5 = Command_SelectBattleshipsFromShortcut ;Command_DaisyCutterFromShortcut
  6 = Command_FireParticleUplinkCannonFromShortcut
  7 = Command_SpySatelliteScanFromShortcut
  8 = Command_F18HornetStrikeFromShortcut
  9 = Command_SpectreGunshipFromShortcut
  10 = Command_LeafletDropFromShortcut
  11 = Command_SelectAircraftCarriersFromShortcut;Command_CIAIntelligenceFromShortcut
END

CommandSet AmericaStrategyCenterCommandSet
  1 = Command_InitiateBattlePlanBombardment
  ;2 = Command_CIAIntelligence
  3 = Command_InitiateBattlePlanHoldTheLine
  4 = Command_AmericaTomahawkRemoteControl
  5 = Command_InitiateBattlePlanSearchAndDestroy
  6 = Command_UpgradeAmericaChemicalSuits
  7 = Command_UpgradeAmericaMOAB
  8 = Command_UpgradeAmericaCompositeArmor
  9 = Command_UpgradeAmericaAdvancedTraining
 10 = Command_UpgradeAmericaDroneArmor
 11 = Command_UpgradeAmbulanceRepairCrew
 12 = Command_UpgradeAmericaSupplyLines
 13 = Command_AmericaUpgradeOICWRifle
 14 = Command_Sell   
End

Object AmericaBarracks
  AddModule
    Behavior = GrantUpgradeCreate ModuleTag_MDUSA04a
    UpgradeToGrant = Upgrade_AmericaRangerFlashBangGrenade
  End
  End
End

Object AmericaStrategyCenter
  AddModule
    Behavior = GrantUpgradeCreate ModuleTag_MDUSA04b
    UpgradeToGrant = Upgrade_AmericaTomahawkRemoteControl
  End
  End
End

