

;WaterTransparency
;  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
;  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
;End


;-----------------
;AI Stuff
;-----------------

AIData
  AICrushesInfantry                   = No    ; If yes, ai will attempt to crush infantry with vehicles.
End


;-----------------------
;Build Limits
;-----------------------

Object GLATankMarauder
Buildable = No
End

Object GLAInfantryJarmenKell
Buildable = No
End

Object GLAVehicleScudLauncher
Buildable = No
End

Object GLAInfantryHijacker
Buildable = No
End

Object GLAStingerSite
Buildable = No
End

Object GLAPalace
Buildable = No
End

Object GLAVehicleRocketBuggy
Buildable = No
End

Object GLAVehicleQuadCannon
Buildable = No
End

Object GLAInfantryAngryMobNexus 
Buildable = No
End

Object GLAInfantryTerrorist
Buildable = No
End

Object GLAVehicleToxinTruck
Buildable = No
End

Object GLAVehicleBombTruck
Buildable = No
End

;Object GLAVehicleRadarVan
;Buildable = No
;End

Object GLACommandCenter
Buildable = No
End

Object GLAScudStorm
Buildable = No
End

Object GLABlackMarket
Buildable = No
End

Object ChinaVehicleNukeLauncher
Buildable = No
End

; Prisons are cut. sorry. (srj)
;Object GLAPrison
;Buildable = No
;End

Object GLADemoTrap
Buildable = No
End

Object ChinaGattlingCannon
Buildable = No
End

Object ChinaAirfield
Buildable = No
End

Object ChinaPropagandaCenter
Buildable = No
End

Object ChinaSpeakerTower
Buildable = No
End

Object ChinaNuclearMissileLauncher
Buildable = No
End

Object ChinaVehicleInfernoCannon
Buildable = No
End

Object ChinaTankDragon
Buildable = No
End

Object ChinaInfantryHacker
Buildable = No
End

Object ChinaVehicleTroopCrawler
Buildable = No
End

Object ChinaTankOverlord
Buildable = No
End

Object ChinaTankGattling
Buildable = No
End

Object ChinaInfantryBlackLotus
Buildable = No
End

Object ChinaNuclearMissileLauncher
Buildable = No
End

WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
End

Upgrade Upgrade_GLAExtraSalvage
  DisplayName        = UPGRADE:ExtraSalvage
  BuildTime          = 1;60.0
  BuildCost          = 0;2500
  ButtonImage        = SSExtraSalvage
  ;ResearchSound      = ScorpionTankVoiceUpgrade
End



