
CommandSet ChinaAirfieldCommandSet
  1 = Command_ConstructChinaJetMIG
  2 = Command_ConstructChinaVehicleHelix
  3 = Command_ConstructChinaJetEMPMIGBomber
  4 = Command_ConstructChinaVehicleTiger
  9 = Command_CarpetBomb
 10 = Command_UpgradeChinaMigAfterBurner
 11 = Command_UpgradeChinaAircraftArmor
 12 = Command_UpgradeChinaHelixArmor
 13 = Command_UpgradeChinaMines
 14 = Command_Sell
End

CommandSet SpecialPowerShortcutChina
  1 = Command_ClusterMinesFromShortcut
  2 = Command_ArtilleryBarrageFromShortcut
  3 = Command_CashHackFromShortcut
  4 = Command_EmergencyRepairFromShortcut
  5 = Command_EMPPulseFromShortcut
  6 = Command_NeutronMissileFromShortcut
  7 = Command_HackedSpySatelliteScanFromShortcut
  8 = Command_ShortcutNapalmStrike
  9 = Command_CarpetBombFromShortcut
  10 = Command_FrenzyFromShortcut
END

Object ChinaAirfield

 AddModule
  Behavior           = OCLSpecialPower ModuleTag_Override01
    SpecialPowerTemplate = SuperweaponCarpetBomb
    OCL                  = SUPERWEAPON_CarpetBomb
    CreateLocation       = CREATE_AT_EDGE_NEAR_SOURCE
  End 
 End

End

Science SCIENCE_CarpetBomb
  PrerequisiteSciences = None
  SciencePurchasePointCost = 0  ; note that this means "not purchasable", NOT "free"!
  IsGrantable = Yes
  DisplayName = SCIENCE:ChinaCarpetBomb
  Description = SCIENCE:ToolTipChinaScienceCarpetBomb
End


Object TrainEngine

  ReplaceModule ModuleTag_01
    Draw = W3DModelDraw ModuleTag_01_Override
      ConditionState  = NONE
        Model         = CVTrnEng2
      End
    End
  End

  ReplaceModule ModuleTag_03
    Behavior              = RailroadBehavior ModuleTag_03_Override
      PathPrefixName    = Railroad
      ;=== PARAMETERS FOR ALL CARRIAGES ===    
      RunningGarrisonSpeedMax = 1
      KillSpeedMin            = 1
      Friction                = 0.995
      BigMetalBounceSound     = BuildingFallingMetal
      SmallMetalBounceSound   = VehicleImpactHeavy
      MeatyBounceSound        = InfantryCrush
      ClicketyClackSound      = TrainClicketyClack
      WhistleSound            = TrainWhistle
      ;=== PARAMETERS THAT ARE MEANINGFUL ONLY WHEN IsLocomotive = Yes
      IsLocomotive         = Yes
      SpeedMax             = 5
      Acceleration         = 1.03
      WaitAtStationTime    = 10000     ; ten seconds
      Braking              = 0.97
      RunningSound         = TrainRunningLoop
      CrashFXTemplateName  = SpecialEffectsTrainCrashObject

      CarriageTemplateName = TrainCar01
      CarriageTemplateName = TrainCar03
      CarriageTemplateName = CabooseFullOfTerrorists
    End
  End

End



Object AmericaJetB52
 ReplaceModule ModuleTag_03
  Body = ActiveBody ModuleTag_03_Override
    MaxHealth       = 500.0
    InitialHealth   = 500.0
  End
 End
 VisionRange         = 300.0 
End
 

Object CINEExplBox
; *** AUDIO Parameters ***
  SoundMoveStart = DaisyCutterWeapon

  ReplaceModule ModuleTag_BODY
    Body            = ActiveBody ModuleTag_BODY_Override
      MaxHealth       = 1000.0
      InitialHealth   = 1000.0
    End
  End

  AddModule
    Behavior = AIUpdateInterface ModuleTag_03
    End
  End
  Locomotor = SET_NORMAL None
  
  ; remove the default die
  RemoveModule ModuleTag_DIE

  AddModule
    Behavior = FireWeaponWhenDeadBehavior ModuleTag_05
      DeathWeapon   = CarpetBombWeapon
      StartsActive  = Yes
    End
  End

  AddModule
    Behavior = HeightDieUpdate ModuleTag_06
      TargetHeight = 1.0
      TargetHeightIncludesStructures = No
    End
  End

  AddModule
    Behavior = SpecialPowerCompletionDie ModuleTag_07
      SpecialPowerTemplate = SuperweaponCarpetBomb
    End
  End

  AddModule
    Behavior = FXListDie ModuleTag_08
      DeathFX = FX_CarpetBomb
    End
  End

  AddModule
    Behavior = DestroyDie ModuleTag_09
      ;nothing
    End
  End
End

; ********* CINEMATIC SETTING **************

AudioEvent CINE_B52AmbientLoop
  Sounds      = vb52lo2a vb52lo2b vb52lo2c
  Attack      = vb52lo1a
  Decay       = vb52lo3a 
  Control     = loop all random
  Volume      = 50
  Limit       = 3
  PitchShift  = -5 5
  Type        = world shrouded everyone
End

WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 1.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
End



;-----------------------
;Build Limits
;-----------------------

;Object GLATankMarauder
;Buildable = No
;End

Object GLAInfantryJarmenKell
Buildable = No
End

;Object GLAVehicleScudLauncher
;Buildable = No
;End

;Object GLAInfantryHijacker
;Buildable = No
;End

;Object GLAStingerSite
;End

;Object GLAPalace
;Buildable = No
;End

;Object GLAVehicleRocketBuggy
;End

;Object GLAVehicleQuadCannon
;Buildable = No
;End

;Object GLAInfantryAngryMobNexus 
;Buildable = No
;End

;Object GLAInfantryTerrorist
;Buildable = No
;End

Object GLAVehicleToxinTruck
Buildable = No
End

Object GLAVehicleBombTruck
Buildable = No
End

;Object GLAVehicleRadarVan
;Buildable = No
;End

;Object GLACommandCenter
;Buildable = No
;End

Object GLAScudStorm
Buildable = No
End

;Object GLABlackMarket
;Buildable = No
;End

;Object GLADemoTrap
;Buildable = No
;End
