;----------------------------------
;-----Set Tech Tree(Buildings)-----
;----------------------------------

Object ChinaAirfield
 Buildable = No
End

;Object ChinaBarracks
;End

;Object ChinaBunker
;End

;Object ChinaCommandCenter
;End

;Object ChinaGattlingCannon
;End

Object ChinaNuclearMissileLauncher
 Buildable = No
End

;Object ChinaPowerPlant
;End

Object ChinaPropagandaCenter
 Buildable = No
End

Object ChinaSpeakerTower
 Buildable = No
End

;Object ChinaSupplyCenter
;End

;Object ChinaWall
;End

;Object ChinaWallHub
;End

;Object ChinaWarFactory
;End

;-------------------
;-----GLA Stuff-----
;-------------------

Object GLAStingerSite
 Buildable = No
End

Object GLATunnelNetwork
 Buildable = No
End

Object GLAPalace
 Buildable = No
End

Object GLABlackMarket
 Buildable = No
End

Object GLAScudStorm
 Buildable = No
End

Object GLADemoTrap
 Buildable = No
End

;------------------------------------------
;-----Set Tech Tree(Infantry/Vehicles)-----
;------------------------------------------

Object ChinaInfantryBlackLotus
 Buildable = No
End

Object ChinaInfantryHacker
 Buildable = No
End

;Object ChinaInfantryRedguard
;End

;Object ChinaInfantryTankHunter
;End

Object ChinaJetMIG
 Buildable = No
End

;Object ChinaTankBattleMaster
;End

;Object ChinaVehicleDozer
;End

;Object ChinaTankDragon
;End

;Object ChinaTankGattling
;End

Object ChinaVehicleInfernoCannon
 Buildable = No
End

Object ChinaTankOverlord
 Buildable = No
End

Object ChinaVehicleNukeLauncher
 Buildable = No
End

Object ChinaVehiclePOWTruck
 Buildable = No
End

Object ChinaVehiclePropagandaBlimp
 Buildable = No
End

Object ChinaVehicleTroopCrawler
 Buildable = No
End

;-------------------
;-----GLA Stuff-----
;-------------------

Object GLAInfantryAngryMobNexus 
 Buildable = No
End

Object GLAInfantryHijacker
 Buildable = No
End

Object GLAInfantryJarmenKell
 Buildable = No
End

Object GLAVehicleRadarVan
 Buildable = No
End

Object GLAVehicleQuadCannon
 Buildable = No
End

Object GLATankScorpion
 Buildable = No
End

Object GLAVehicleScudLauncher
 Buildable = No
End

Object GLATankMarauder
 Buildable = No
End

Object GLAVehicleRocketBuggy
 Buildable = No
End

Object GLAVehicleBombTruck
 Buildable = No
End


;------------------------------------------
;-----------Set Object Overrides-----------
;------------------------------------------

Locomotor BasicCarLocomotor
  Speed = 60                ; in dist/sec
End

Locomotor PanicCarLocomotor
  Speed = 70                ; in dist/sec
End

Object CarAsian1
  CrusherLevel = 0
END

Object CarAsian2
  CrusherLevel = 0
END

Object CarCompact
  CrusherLevel = 0
END

Object CarLimo1
  CrusherLevel = 0
END

Object CarLimo2
  CrusherLevel = 0
END

Object CarLimo3
  CrusherLevel = 0
END

Object CarLuxury01
  CrusherLevel = 0
END

Object CarLuxury02
  CrusherLevel = 0
END

Object CarLuxury03
  CrusherLevel = 0
END

Object CarLuxury04
  CrusherLevel = 0
END

Object CarSedan01
  CrusherLevel = 0
END

Object CarSport01
  CrusherLevel = 0
END

Object CarSport02
  CrusherLevel = 0
END

Object CarSwatchEuro
  CrusherLevel = 0
END

Object CarTaxiCab05
  CrusherLevel = 0
END

Object OceanConventionCenter
 KindOf = +IMMUNE_TO_CAPTURE
 ReplaceModule ModuleTag_02
  Body                  = ActiveBody ModuleTag_02_Override
    MaxHealth       = 5000.0
    InitialHealth   = 5000.0
  End
 End
  ReplaceModule ModuleTag_03
    Behavior = GarrisonContain ModuleTag_03_Override
      ContainMax          = 0
      EnterSound          = GarrisonEnter
      ExitSound           = GarrisonExit
    End
  End
END

Object AsianMegaHotel01
 ReplaceModule ModuleTag_02
  Body                  = ActiveBody ModuleTag_02_Override
    MaxHealth       = 5000.0
    InitialHealth   = 5000.0
  End
 End
END

Object EuropeanParkingGarage
 KindOf = +IMMUNE_TO_CAPTURE
  ReplaceModule ModuleTag_03
    Behavior = GarrisonContain ModuleTag_03_Override
      ContainMax          = 0
      EnterSound          = GarrisonEnter
      ExitSound           = GarrisonExit
    End
  End
END

Object AsianTrainStation02
  ReplaceModule ModuleTag_03
    Behavior = GarrisonContain ModuleTag_03_Override
      ContainMax          = 0
      EnterSound          = GarrisonEnter
      ExitSound           = GarrisonExit
    End
  End
END


;------------------------------------------------------------------------------

WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
End

;------------------------------------------------------------------------------
;******************** Cinematic parameters ************************************

Object CINEExplBox

  ; remove the default die
  RemoveModule ModuleTag_DIE

  AddModule
    Behavior = InstantDeathBehavior ModuleTag_05
      FX = WeaponFX_SCUDMissileDetonationExplosive
    End
  End
  
End