;/////////////////////////////////////////////////
;//                                             //
;//             China Mission 6                 //
;//                                             //
;/////////////////////////////////////////////////


;----------------------------------
;-----Set Tech Tree(Buildings)-----
;----------------------------------
Upgrade Upgrade_InfantryCaptureBuilding
  DisplayName        = UPGRADE:RangerCaptureBuilding
  BuildTime          = 1.0
  BuildCost          = 0
  ButtonImage        = SSCaptureBuilding
End

Upgrade Upgrade_ChinaChainGuns
  DisplayName        = UPGRADE:ChainGuns
  BuildTime          = 1.0
  BuildCost          = 0
  ButtonImage        = SSGattling
  ResearchSound      = GattlingTankVoiceUpgrade
End

Upgrade Upgrade_ChinaBlackNapalm
  DisplayName        = UPGRADE:BlackNapalm
  BuildTime          = 1.0
  BuildCost          = 0
  ButtonImage        = SSBlackNapalm
  ResearchSound      = DragonTankVoiceUpgradeBlackNapalm
End

Upgrade Upgrade_ChinaLotusSystemHack
  DisplayName        = UPGRADE:SystemHack
  BuildTime          = 1.0
  BuildCost          = 0
  ButtonImage        = SNLotusSystemHack
End




Object ChinaAirfield
 Buildable = No
End

Object ChinaBarracks
 Buildable = No
End

Object ChinaBunker
 Buildable = No
End

Object ChinaCommandCenter
 Buildable = No
End

Object ChinaGattlingCannon
 Buildable = No
End

Object ChinaMoat
 Buildable = No
End

Object ChinaNuclearMissileLauncher
 Buildable = No
End

Object ChinaPowerPlant
 Buildable = No
End

Object ChinaPropagandaCenter
 Buildable = No
End

Object ChinaSpeakerTower
 Buildable = No
End

Object ChinaSupplyCenter
 Buildable = No
End

Object ChinaWarFactory
 Buildable = No
End

Object GLACommandCenter
 Buildable = No
End

Object GLABlackMarket
 Buildable = No
End

Object GLAScudStorm
 Buildable = No
End

Object GLADemoTrap
 Buildable = No
End

Object GLATunnelNetwork
 Buildable = No
End

Object GLAStingerSite
 Buildable = No
End

Object GLAPalace
 Buildable = No
End

Object GLASupplyStash
 Buildable = No
End

Object GLABarracks
 Buildable = No
End

Object GLAArmsDealer
 Buildable = No
End

;------------------------------------------
;-----Set Tech Tree(Infantry/Vehicles)-----
;------------------------------------------

Object ChinaInfantryBlackLotus
 Buildable = Yes
End

Object ChinaInfantryHacker
 Buildable = No
End

;Object ChinaInfantryRedguard
;End

;Object ChinaInfantryTankHunter
;End

Object ChinaJetMIG
 Buildable = No
End

;Object ChinaTankBattleMaster
;End

Object ChinaVehicleDozer
 Buildable = No
End

;Object ChinaTankDragon
;End

;Object ChinaTankGattling
;End

Object ChinaVehicleInfernoCannon
 Buildable = No
End

Object ChinaTankOverlord
 Buildable = No
End

Object ChinaVehicleNukeLauncher
 Buildable = No
End

;Object ChinaVehicleTroopCrawler
;End

;Object GLAInfantryWorker
;End

Object GLAInfantryRebel
 Buildable = No
End

Object GLAInfantryJarmenKell
 Buildable = No
End

Object GLAInfantryTunnelDefender
 Buildable = No
End

Object GLAInfantryTerrorist
 Buildable = No
End

Object GLAInfantryHijacker
 Buildable = No
End

Object GLAVehicleRocketBuggy
 Buildable = No
End

Object GLATankScorpion
 Buildable = No
End

Object GLAVehicleToxinTruck
 Buildable = No
End

Object GLAVehicleBombTruck
 Buildable = No
End

Object GLAVehicleScudLauncher
 Buildable = No
End


;------------------------------------
;---------Object Overrides-----------
;------------------------------------

Object SoccerStadiumBleacherEnd
 KindOf = +IMMUNE_TO_CAPTURE
End

Object SoccerStadiumField
 KindOf = +IMMUNE_TO_CAPTURE
End

Object SoccerStadiumEntrance
 KindOf = +IMMUNE_TO_CAPTURE
End

Object SoccerStadiumGoal
 KindOf = +IMMUNE_TO_CAPTURE
End

Object SoccerStadiumSideBleachers
 KindOf = +IMMUNE_TO_CAPTURE
End

Object SoccerStadiumLight
 KindOf = +IMMUNE_TO_CAPTURE
End

Object StanWatchTowerTall
 KindOf = +IMMUNE_TO_CAPTURE
End

Object StanTallTower
 KindOf = +IMMUNE_TO_CAPTURE
End

Object MogadishuTower05
 KindOf = +IMMUNE_TO_CAPTURE
End



;--------------------------------------------------------------

WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
End


;--------------------------------------------------------------
;Cinematics Entries
;---------------------------------------------------------

Object CINE_TrainEngine
  ReplaceModule ModuleTag_03

  Behavior = RailroadBehavior ModuleTag_03_Override

    PathPrefixName    = Railroad




    ;=== PARAMETERS FOR ALL CARRIAGES ===    
    RunningGarrisonSpeedMax = 1
    KillSpeedMin            = 1
    Friction                = 0.995
    BigMetalBounceSound     = BuildingFallingMetal
    SmallMetalBounceSound   = VehicleImpactHeavy
    MeatyBounceSound        = InfantryCrush
    ClicketyClackSound      = TrainClicketyClack
    WhistleSound            = TrainWhistle

    ;=== PARAMETERS THAT ARE MEANINGFUL ONLY WHEN IsLocomotive = Yes
    IsLocomotive         = Yes
    SpeedMax             = 5
    Acceleration         = 1.03
    WaitAtStationTime    = 100     ; CINEMATIC: shorter wait time
    Braking              = .97
    RunningSound         = TrainRunningLoop
    CrashFXTemplateName  = SpecialEffectsTrainCrashObject

    CarriageTemplateName = TrainCar03
    CarriageTemplateName = TrainCar03
    CarriageTemplateName = TrainCoal    
    CarriageTemplateName = TrainCab

    ;CarriageTemplateName = TrainCar01
    ;CarriageTemplateName = TrainCar02
    ;CarriageTemplateName = TrainCar03
    ;CarriageTemplateName = TrainCoal    
    ;CarriageTemplateName = TrainTank
    ;CarriageTemplateName = CabooseFullOfTerrorists
  End
End
End


;----Audio---
Object Fountain1
 SoundAmbient = NoSound
End

Object Fountain2
 SoundAmbient = NoSound
End
