;----------------------------------
;-----Set Tech Tree(Buildings)-----
;----------------------------------

;Object ChinaAirfield
;End

;Object ChinaBarracks
;End

;Object ChinaBunker
;End

Object ChinaCommandCenter
  BuildTime         = 25.0           ; in seconds
End

;Object ChinaGattlingCannon
;End

Object ChinaNuclearMissileLauncher
 Buildable = No
End

;Object ChinaPowerPlant
;End

Object ChinaPropagandaCenter
 Buildable = No
End

;Object ChinaSpeakerTower
;End

;Object ChinaSupplyCenter
;End

;Object ChinaWarFactory
;End

;------------------------------------------
;-----Set Tech Tree(Infantry/Vehicles)-----
;------------------------------------------

;Object ChinaInfantryBlackLotus
;End

Object ChinaInfantryHacker
 Buildable = No
End

;Object ChinaInfantryRedguard
;End

;Object ChinaInfantryTankHunter
;End

;Object ChinaJetMIG
;End

;Object ChinaTankBattleMaster
;End

;Object ChinaVehicleDozer
;End

;Object ChinaTankDragon
;End

;Object ChinaTankGattling
;End

Object ChinaVehicleInfernoCannon
 Buildable = No
End

Object ChinaTankOverlord
 Buildable = No
End

Object ChinaVehicleNukeLauncher
 Buildable = No
End

;Object ChinaVehicleTroopCrawler
;End

;------------------------------------------
;-----------Set Object Overrides-----------
;------------------------------------------

Object Dam
 KindOf = +IMMUNE_TO_CAPTURE
END

WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
End


Object CINEExplBox
  RemoveModule ModuleTag_DIE  

  AddModule ModuleTag_05  
    Behavior = FXListDie ModuleTag_05
      DeathFX = FX_HumveeExplosionOneFinal
    End
  End
End

MusicTrack Cin_China03
  Filename = C_Chi03.mp3
End

AudioEvent BridgeDamaged
  Sounds =  gbridama gbridamb
  Control = random
  Volume = 120
  Limit = 2
  Priority    = normal
  Type = world shrouded everyone
End

AudioEvent BuildingDamagedStateLight
  Sounds      = gbuidama gbuidamb gbuidamc gbuidamd gbuidame gbuidamf gbuidamg
  Control     = random interrupt
  VolumeShift = -20
  PitchShift  = -20  20
  Limit       = 2
  Volume      = 120
  Priority    = normal
  Type        = world shrouded everyone
End

;-----------------------
;Build Limits
;-----------------------

Object GLATankMarauder
Buildable = No
End

Object GLAInfantryJarmenKell
Buildable = No
End

Object GLAVehicleScudLauncher
Buildable = No
End

Object GLAInfantryHijacker
Buildable = No
End

;Object GLAStingerSite
;End

Object GLAPalace
Buildable = No
End

;Object GLAVehicleRocketBuggy
;End

Object GLAVehicleQuadCannon
Buildable = No
End

Object GLAInfantryAngryMobNexus 
Buildable = No
End

;Object GLAInfantryTerrorist
;Buildable = No
;End

Object GLAVehicleToxinTruck
Buildable = No
End

Object GLAVehicleBombTruck
Buildable = No
End

;Object GLAVehicleRadarVan
;Buildable = No
;End

;Object GLACommandCenter
;Buildable = No
;End

Object GLAScudStorm
Buildable = No
End

Object GLABlackMarket
Buildable = No
End

;Object ChinaVehicleNukeLauncher
;Buildable = No
;End

Object GLADemoTrap
Buildable = No
End