;-----------------
;AI Stuff
;-----------------

AIData

  AICrushesInfantry                   = No ; If yes, ai will attempt to crush infantry with vehicles.
End

Object CINEExplBox

  ; remove the default die
  RemoveModule ModuleTag_DIE

  AddModule
    Behavior = InstantDeathBehavior ModuleTag_05
      FX = FX_HumveeExplosionOneFinal
    End
  End
  
End

Object ChinaWarFactory
  CommandSet       = ChinaWarFactoryCommandSet_CHI01
END

CommandSet ChinaWarFactoryCommandSet_CHI01
  1  = Command_ConstructChinaTankBattleMaster
  2  = Command_ConstructChinaVehicleTroopCrawler
  3  = Command_ConstructChinaTankDragon
  13 = Command_UpgradeChinaMines
  14 = Command_Sell
End

;------------------------------------------------------------------------------
Object NuclearBunker
  KindOf = +IMMUNE_TO_CAPTURE
END

WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
  SkyboxTextureN = TSMrnCldy_N.tga
  SkyboxTextureE = TSMrnCldy_E.tga
  SkyboxTextureS = TSMrnCldy_S.tga
  SkyboxTextureW = TSMrnCldy_W.tga
  SkyboxTextureT = TSMrnCldy_T.tga
End

;--------------------------


Object AsianNightClub 
  SoundAmbient = NoSound
End

Object AncientGazebo
  SoundAmbient = NoSound
End

Weapon CINE_BuggyRocketWeapon
  PrimaryDamage               = 20.0            
  PrimaryDamageRadius         = 0.0      
  ScatterRadiusVsInfantry     = 20.0     ;When this weapon is used against infantry, it can randomly miss by as much as this distance.
  SecondaryDamage             = 5.0          
  SecondaryDamageRadius       = 10.0    
  AttackRange                 = 300.0   
  MinimumAttackRange          = 300.0 ;150.0 ; Rockets take some distance to target, and you don't want them to blow up in your face.
  DamageType                  = EXPLOSION          ; ignored for projectile weapons
  DeathType                   = EXPLODED
  WeaponSpeed                 = 600               ; ignored for projectile weapons
  ProjectileDetonationFX      = WeaponFX_RocketBuggyMissileDetonation
  ProjectileObject            = RocketBuggyMissile
  ProjectileExhaust           = MissileExhaust
  VeterancyProjectileExhaust  = HEROIC HeroicMissileExhaust
  RadiusDamageAffects         = ALLIES ENEMIES NEUTRALS
  ScatterRadius               = 0      ; This weapon will scatter somewhere within a circle of this radius, instead of hitting someone directly
  DelayBetweenShots           = 200  ; time between shots, msec
  ClipSize                    = 6            ; how many shots in a Clip (0 == infinite)
  ClipReloadTime              = 10    ; how long to reload a Clip, msec
  AutoReloadsClip             = Yes 
  FireFX                      = FX_BuggyMissileIgnition
  FireSound                   = RocketBuggyWeapon 
  WeaponBonus                 = PLAYER_UPGRADE DAMAGE 125% ; AP rocket upgrade
  ProjectileCollidesWith      = STRUCTURES
End



