;-----------------
;AI Stuff
;-----------------

AIData

  AICrushesInfantry                   = No ; If yes, ai will attempt to crush infantry with vehicles.

End

;-----------------------
;Build Limits
;-----------------------

Object AmericaSupplyDropZone
Buildable = No
End

Object AmericaAirfield
Buildable = No
End

Object AmericaPatriotBattery
Buildable = No
End

Object AmericaParticleCannonUplink
Buildable = No
End

Object AmericaStrategyCenter
Buildable = No
End

Object AmericaDetentionCamp
Buildable = No
End

Object AmericaCommandCenter
Buildable = No
End

Object AmericaVehicleTomahawk
Buildable = No
End

;Object AmericaVehicleChinook
;Buildable = No
;End

Object AmericaVehicleMedic
Buildable = No
End

;Object AmericaTankCrusader
;Buildable = No
;End

;Object AmericaTankPaladin
;Buildable = No
;End

;Object AmericaVehicleDozer
;Buildable = No
;End

Object AmericaInfantryRangerMissileTeam
Buildable = No
End

Object AmericaInfantryColonelBurton
Buildable = No
End

Object GLAPalace
Buildable = No
End

Object GLABlackMarket
Buildable = No
End

Object GLAScudStorm
Buildable = No
End

; Prisons are cut. sorry. (srj)
;Object GLAPrison
;Buildable = No
;End

Object GLADemoTrap
Buildable = No
End

Object GLAVehicleRocketBuggy
Buildable = No
End

Object GLAVehicleToxinTruck
Buildable = No
End

Object GLAInfantryAngryMobNexus 
Buildable = No
End

Object GLAVehicleQuadCannon
Buildable = No
End

Object GLAVehicleBombTruck
Buildable = No
End

Object GLAInfantryTerrorist
Buildable = No
End

Object GLAInfantryJarmenKell
Buildable = No
End

Object GLAVehicleScudLauncher
Buildable = No
End

Object GLATankMarauder
Buildable = No
End

Object GLAInfantryHijacker
Buildable = No
End

Object AmericaInfantryPathfinder
Buildable = No
End

;Object WatchTower03
;  Behavior = GarrisonContain ModuleTag_03
;    ContainMax          = 0
;    EnterSound          = GarrisonEnter
;    ExitSound           = GarrisonExit
;  End
;ENd

WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
End







