#!/usr/bin/env python3
"""Build zzz-ZZZZZZZRotrInfantry.big — Rise of the Reds Shmel Trooper +
Shock Trooper ported to Kwai (China Tank General) for the ShockWave /
GeneralsX stack.

TWO-PHASE DESIGN (read the README):
  Phase 1 (this script, side branch): ships everything EXCEPT command-set
  wiring — object INIs, baked shared INI files (today's effective copy +
  our appends), mapped images, W3D models, textures.  The archive is NOT
  installed anywhere and is deliberately inert: no build button references
  the units yet.
  Phase 2 (integrate.py, merge day): re-derives every shared INI file from
  the THEN-current effective space + the fragments/ dir, adds the barracks
  buttons (slots parameterized) and the Generals.str entries, repacks the
  archive in place.

Usage:  python3 build.py
"""
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
WORK = os.path.join(HERE, "work")
sys.path.insert(0, WORK)
sys.path.insert(0, os.path.join(HERE, "..", "hotkey-addon"))
sys.path.insert(0, os.path.join(HERE, "..", "chaos-units", "work"))

from bigfile import BigEntry, write_big_file, read_big  # noqa: E402
from iniblocks import load_tree, parse_blocks  # noqa: E402
import portdefs  # noqa: E402
import portlib  # noqa: E402
from portlib import (edit_block, retoken, AUDIO_REMAP, FX_REMAP,  # noqa: E402
                     PREREQ_REMAP, OBJECT_FILES, SHARED_APPENDS, MAPPED_IMAGES)
import rotrfetch  # noqa: E402
import resolve_art  # noqa: E402
import verify_lib  # noqa: E402

ARCHIVE = portdefs.ARCHIVE_NAME
FRAG_DIR = os.path.join(HERE, "fragments")
EXTRACT_DIR = os.path.join(HERE, "extracted")

HEADER = ("; ===================================================================\n"
          "; ROTR infantry port (side/rotr-infantry): Shmel Trooper + Shock\n"
          "; Trooper re-sided for Kwai.  Generated by rotr-infantry/build.py --\n"
          "; do not hand-edit; see rotr-infantry/README.md.\n"
          "; ===================================================================\n\n")

APPEND_BANNER = ("\n\n; ===================================================================\n"
                 "; appended by rotr-infantry (side/rotr-infantry) -- ROTR Shmel\n"
                 "; Trooper + Shock Trooper closure.  Regenerated at merge time by\n"
                 "; rotr-infantry/integrate.py; the base content above is the\n"
                 "; effective copy of this file at build time.\n"
                 "; ===================================================================\n\n")


def token_map():
    m = dict(portdefs.RENAMES)
    m.update(PREREQ_REMAP)
    m.update(FX_REMAP)
    m.update(AUDIO_REMAP)
    return m


def side_fix(name, text):
    if name in ("RussianInfantryShmelTrooper", "RussiaInfantryShockTrooper",
                "RussiaInfantryShockTrooper_Var1"):
        text, n = re.subn(r"^(\s*Side\s*=\s*)Russia\b", r"\1ChinaTankGeneral",
                          text, flags=re.M)
        assert n >= 1, "no Side line found in %s" % name
    return text


# --------------------------------------------------------------- fragments
UNIT_COMMANDSETS = """CommandSet Tank_ChinaInfantryShmelTrooperCommandSet
  1  = Tank_Command_ShmelTrooperSmokeRocket
  3  = Tank_Command_ShmelTrooperAntiToxinRocket
  11 = Command_AttackMove
  13 = Command_Guard
  14 = Command_Stop
End

CommandSet Tank_ChinaInfantryShockTrooperCommandSet
  1  = Tank_Command_ShockTrooperSwitchToRockets
  3  = Tank_Command_ShockTrooperSwitchToTeslaGun
  11 = Command_AttackMove
  13 = Command_Guard
  14 = Command_Stop
End
"""

CONSTRUCT_BUTTONS = """CommandButton Tank_Command_ConstructChinaInfantryShmelTrooper
  Command           = UNIT_BUILD
  Object            = Tank_ChinaInfantryShmelTrooper
  TextLabel         = CONTROLBAR:ConstructTankShmelTrooper
  ButtonImage       = SRShmelTrooper
  ButtonBorderType  = BUILD
  DescriptLabel     = CONTROLBAR:ToolTipTankBuildShmelTrooper
  UnitSpecificSound = MoneyWithdraw
End

CommandButton Tank_Command_ConstructChinaInfantryShockTrooper
  Command           = UNIT_BUILD
  Object            = Tank_ChinaInfantryShockTrooper
  TextLabel         = CONTROLBAR:ConstructTankShockTrooper
  ButtonImage       = SRShockTrooper
  ButtonBorderType  = BUILD
  DescriptLabel     = CONTROLBAR:ToolTipTankShockTrooper
  UnitSpecificSound = MoneyWithdraw
End
"""

# our string keys -> donor keys in ROTR's Data\Generals.str (fetched from
# !Rotr_English.gib); None = composed by hand
STR_FROM_DONOR = [
    ("OBJECT:TankShmelTrooper", "OBJECT:ShmelTrooper"),
    ("OBJECT:TankShockTrooper", "OBJECT:ShockTrooper"),
    ("CONTROLBAR:ConstructTankShmelTrooper", "CONTROLBAR:ConstructRussiaInfantryShmelTrooper"),
    ("CONTROLBAR:ToolTipTankBuildShmelTrooper", "CONTROLBAR:ToolTipRussiaBuildShmelTrooper"),
    ("CONTROLBAR:ConstructTankShockTrooper", "CONTROLBAR:ConstructRussiaShockTrooper"),
    ("CONTROLBAR:ToolTipTankShockTrooper", "CONTROLBAR:ToolTipRussiaShockTrooper"),
    ("CONTROLBAR:TankShmelSmokeRocket", "CONTROLBAR:RPGConscriptShmelRocket"),
    ("CONTROLBAR:ToolTipTankShmelSmokeRocket", "CONTROLBAR:ToolTipRussiaRPGConscriptShmelRocket"),
    ("CONTROLBAR:TankShmelAntiToxinRocket", "CONTROLBAR:ShmelAntiToxinRocket"),
    ("CONTROLBAR:ToolTipTankShmelAntiToxinRocket", "CONTROLBAR:ToolTipRussiaShmelAntiToxinRocket"),
    ("CONTROLBAR:TankShockTrooperRocketsMode", "CONTROLBAR:HERocketsMode"),
    ("CONTROLBAR:ToolTipTankShockTrooperRocketsMode", "CONTROLBAR:ToolTipSwitchToRussiaHERockets"),
    ("CONTROLBAR:TankShockTrooperTeslaMode", "CONTROLBAR:ElectricRocketsMode"),
    ("CONTROLBAR:ToolTipTankShockTrooperTeslaMode", "CONTROLBAR:ToolTipSwitchToRussiaElectricRockets"),
]

# label-key remap applied to the ability buttons' donor text
LABEL_RENAMES = {
    "CONTROLBAR:RPGConscriptShmelRocket": "CONTROLBAR:TankShmelSmokeRocket",
    "CONTROLBAR:ToolTipRussiaRPGConscriptShmelRocket": "CONTROLBAR:ToolTipTankShmelSmokeRocket",
    "CONTROLBAR:ShmelAntiToxinRocket": "CONTROLBAR:TankShmelAntiToxinRocket",
    "CONTROLBAR:ToolTipRussiaShmelAntiToxinRocket": "CONTROLBAR:ToolTipTankShmelAntiToxinRocket",
    "CONTROLBAR:HERocketsMode": "CONTROLBAR:TankShockTrooperRocketsMode",
    "CONTROLBAR:ToolTipSwitchToRussiaHERockets": "CONTROLBAR:ToolTipTankShockTrooperRocketsMode",
    "CONTROLBAR:ElectricRocketsMode": "CONTROLBAR:TankShockTrooperTeslaMode",
    "CONTROLBAR:ToolTipSwitchToRussiaElectricRockets": "CONTROLBAR:ToolTipTankShockTrooperTeslaMode",
}


def donor_strings():
    fp = os.path.join(HERE, "cache", "fetched", "Rotr_English", "Data", "Generals.str")
    if not os.path.exists(fp):
        rotrfetch.RotrArt().fetch("Data\\Generals.str")
    raw = open(fp, "rb").read().decode("latin-1")
    pat = re.compile(r"^([A-Za-z0-9_]+:[A-Za-z0-9_\-]+)[ \t]*\r?\n(.*?)\r?\nEND",
                     re.S | re.M)
    return {m.group(1).lower(): m.group(2).strip() for m in pat.finditer(raw)}


def build_str_fragment():
    donor = donor_strings()
    out = []
    for ours, theirs in STR_FROM_DONOR:
        text = donor[theirs.lower()]
        # donor text fixes (documented in README):
        # - drop the berserker flavor line (mechanic not ported)
        text = text.replace('\\n Fights harder when a nearby comrade falls.', "")
        # - donor typo: doubled closing quote on the Shock Trooper tooltip
        text = re.sub(r'""\s*$', '"', text)
        assert text.startswith('"') and text.endswith('"') and text.count("\n") == 0, \
            "unexpected donor string shape for %s: %r" % (theirs, text)
        out.append("%s\n%s\nEND\n" % (ours, text))
    return "\n".join(out)


def ability_buttons(ddefs):
    out = []
    for name in ("Command_RussiaShmellTrooperSmokeRocket",
                 "Command_RussiaShmellTrooperAntiToxinRocket",
                 "Command_RussiaShockTrooperSwitchToRockets",
                 "Command_RussiaShockTrooperSwitchToTeslaGun"):
        _rel, text = ddefs[("CommandButton", name)]
        # drop the ROTR science gate on the tesla switch (Kwai can't buy
        # SCIENCE_TeslaTech); also the donor's empty "Science =" line
        text, _ = portlib.strip_lines(text, r"^\s*Science\s*=")
        text = retoken(text, token_map())
        text = retoken(text, LABEL_RENAMES)
        out.append(text.rstrip() + "\n")
    return "\n".join(out)


# ------------------------------------------------------------------- main
def main():
    print("== extracting effective INI space (fresh) ==")
    subprocess.run([sys.executable, os.path.join(WORK, "extract_effective.py")],
                   check=True, stdout=subprocess.DEVNULL)

    print("== parsing trees ==")
    ddefs, dbyname = load_tree(portdefs.DONOR_INI)
    tmap = token_map()

    # ---------------- object files
    entries = {}   # internal path -> bytes
    shipped_ini = {}   # internal path -> final text (for verification)
    for path, blocks in OBJECT_FILES.items():
        parts = [HEADER]
        for t, name in blocks:
            _rel, text = ddefs[(t, name)]
            text = edit_block(t, name, text)
            text = side_fix(name, text)
            text = retoken(text, tmap)
            parts.append(text.rstrip() + "\n\n")
        final = "".join(parts)
        shipped_ini[path] = final
        entries[path] = final.encode("latin-1")

    # ---------------- shared-file fragments + baked copies
    os.makedirs(FRAG_DIR, exist_ok=True)
    frag_texts = {}
    for fname, names in SHARED_APPENDS.items():
        parts = []
        for name in names:
            key = None
            for t in ("Weapon", "Armor", "Locomotor", "FXList", "ParticleSystem",
                      "ObjectCreationList"):
                if (t, name) in ddefs:
                    key = (t, name)
                    break
            assert key, "donor block not found: %s" % name
            _rel, text = ddefs[key]
            text = edit_block(key[0], name, text)
            text = retoken(text, tmap)
            parts.append(text.rstrip() + "\n\n")
        frag_texts[fname] = "".join(parts)

    frag_texts["CommandSet.ini"] = UNIT_COMMANDSETS
    frag_texts["CommandButton.ini"] = ability_buttons(ddefs) + "\n" + CONSTRUCT_BUTTONS
    frag_texts["Generals.str"] = build_str_fragment()

    for fname, text in frag_texts.items():
        with open(os.path.join(FRAG_DIR, fname + ".frag"), "w", newline="\n") as f:
            f.write(text)
    print("wrote %d fragments" % len(frag_texts))

    # bake shared INI files (effective copy + appends); command wiring is NOT baked
    for fname in SHARED_APPENDS:
        eff_fp = os.path.join(WORK, "effective", "Data", "INI", fname)
        base_bytes = open(eff_fp, "rb").read()
        baked = base_bytes + APPEND_BANNER.encode("latin-1") + \
            frag_texts[fname].encode("latin-1")
        path = "Data\\INI\\" + fname
        entries[path] = baked
        shipped_ini[path] = baked.decode("latin-1")

    # ---------------- mapped images (force-ship pages under Rotr_ names)
    donor_mi, _ = load_tree(os.path.join(portdefs.DONOR_INI, "MappedImages"))
    art = rotrfetch.RotrArt()
    page_rename = {}
    mi_parts = [HEADER]
    for name in MAPPED_IMAGES:
        _rel, text = donor_mi[("MappedImage", name)]
        m = re.search(r"^\s*Texture\s*=\s*([A-Za-z0-9_\-\.]+)", text, re.M)
        page = m.group(1)                     # e.g. SNRUserInterface512_002.tga
        if page not in page_rename:
            page_rename[page] = "Rotr_" + page
        text = text.replace(page, page_rename[page])
        mi_parts.append(text.rstrip() + "\n\n")
    mi_path = "Data\\INI\\MappedImages\\HandCreated\\RotrInfantryMappedImages.INI"
    mi_final = "".join(mi_parts)
    entries[mi_path] = mi_final.encode("latin-1")
    shipped_ini[mi_path] = mi_final

    for page, new in sorted(page_rename.items()):
        _ipath, local = art.fetch(page)
        entries["Art\\Textures\\" + new] = open(local, "rb").read()
    print("mapped-image pages shipped (renamed): %s" % sorted(page_rename.values()))

    # ---------------- W3D + texture closure
    art_needed = collect_art_tokens(shipped_ini)
    json.dump(art_needed, open(os.path.join(WORK, "art_needed.json"), "w"), indent=1)
    manifest = resolve_art_assets(art_needed)
    for ipath, local in manifest["ship"]:
        entries[ipath] = open(local, "rb").read()

    # ---------------- write archive
    big_entries = [BigEntry(p, entries[p]) for p in sorted(entries, key=str.lower)]
    out_fp = os.path.join(HERE, ARCHIVE)
    write_big_file(big_entries, out_fp)
    print("wrote %s: %d files, %.1f MB" % (
        ARCHIVE, len(big_entries), os.path.getsize(out_fp) / 1e6))

    # extracted/ mirror for eyeballing
    for p, data in entries.items():
        fp = os.path.join(EXTRACT_DIR, p.replace("\\", "/"))
        os.makedirs(os.path.dirname(fp), exist_ok=True)
        open(fp, "wb").write(data)

    # build manifest for README/integrate bookkeeping
    owners = json.load(open(os.path.join(WORK, "owners.json")))
    json.dump({
        "baked_shared_sources": {("Data\\INI\\" + f): owners.get("Data\\INI\\" + f)
                                 for f in SHARED_APPENDS},
        "art_shipped": sorted(p for p, _ in manifest["ship"]) +
                       sorted("Art\\Textures\\" + v for v in page_rename.values()),
        "art_reused_from_base": sorted("%s (%s)" % (t, o) for t, o in manifest["base"]),
        "page_renames": page_rename,
    }, open(os.path.join(WORK, "build_manifest.json"), "w"), indent=1)

    # ---------------- verification
    print("== verification ==")
    verify_lib.verify_all(out_fp, frag_texts, dbyname)
    print("BUILD OK")


# ------------------------------------------------------------- art helpers
ART_LINE = re.compile(
    r"^\s*(Model|ModelNames|Animation|IdleAnimation|AnimationSet)\s*=\s*(.+)$", re.M)
TEX_LINE = re.compile(
    r"^\s*(Texture|ParticleName|ShadowTexture)\s*=\s*([A-Za-z0-9_\-\.; ]+)$", re.M)


def collect_art_tokens(shipped_ini):
    models, textures = set(), set()
    for path, text in shipped_ini.items():
        if not path.lower().endswith(".ini"):
            continue
        # only OUR appended/object content: for baked shared files, scan only
        # the appended tail (base content is the effective space's business)
        if path.startswith("Data\\INI\\") and "\\" not in path[len("Data\\INI\\"):]:
            text = text.split("appended by rotr-infantry", 1)[-1]
        if "MappedImages" in path:
            continue   # pages handled separately
        for m in ART_LINE.finditer(text):
            val = portlib.strip_comments_line(m.group(2))
            for tok in re.findall(r"[A-Za-z0-9_\-\.]+", val):
                if tok.upper() in ("NONE",) or re.match(r"^[\d\.\-]+$", tok):
                    continue
                for part in tok.split("."):
                    if part and not re.match(r"^[\d\-]+$", part):
                        models.add(part)
        for m in TEX_LINE.finditer(text):
            val = portlib.strip_comments_line(m.group(2)).strip().rstrip(";").strip()
            for tok in re.findall(r"[A-Za-z0-9_\-\.]+", val):
                if tok.upper() == "NONE":
                    continue
                textures.add(tok.rsplit(".", 1)[0])
    return {"models": sorted(models), "textures": sorted(textures)}


def resolve_art_assets(art_needed):
    base = resolve_art.base_art_index()
    rotr = rotrfetch.RotrArt()
    manifest = {"ship": [], "base": [], "missing": []}
    fetched_w3d = []
    for tok in art_needed["models"]:
        f = tok.lower() + ".w3d"
        if f in base:
            manifest["base"].append((tok, base[f]))
            continue
        hit = rotr.find(tok + ".w3d")
        if not hit:
            manifest["missing"].append(("w3d", tok))
            continue
        path, local = rotr.fetch(hit[1])
        manifest["ship"].append((path, local))
        fetched_w3d.append(local)

    tex_all = set(t.lower() for t in art_needed["textures"])
    for local in fetched_w3d:
        for t in resolve_art.w3d_texture_names(local):
            tex_all.add(t.rsplit(".", 1)[0].lower())
    for tok in sorted(tex_all):
        cands = [tok + ".dds", tok + ".tga"]
        in_base = [c for c in cands if c in base]
        if in_base:
            manifest["base"].append((tok, base[in_base[0]]))
            continue
        hit = None
        for c in cands:
            hit = rotr.find(c)
            if hit:
                break
        if not hit:
            manifest["missing"].append(("texture", tok))
            continue
        path, local = rotr.fetch(hit[1])
        manifest["ship"].append((path, local))

    if manifest["missing"]:
        raise SystemExit("MISSING ART: %r" % manifest["missing"])
    return manifest


if __name__ == "__main__":
    main()
