Object 55GallonDrum

  DisplayName      = OBJECT:Barrel
  
  AddModule 
    Behavior                   = SlowDeathBehavior ModuleTag_MapOverride01
      DestructionDelay         = 200
      DestructionDelayVariance = 300
      FX                       = FINAL FX_BarrelDeathExplosion
      OCL                      = FINAL OCL_CreateDamagedBarrel
      Weapon                   = FINAL BarrelWeapon
    End
  End
  
  AddModule
    Behavior        = FireWeaponWhenDeadBehavior ModuleTag_MapOverride02
      DeathWeapon   = ToxinShellWeapon
      StartsActive  = Yes 
    End
  End
  
  AddModule
    Behavior = FireWeaponWhenDamagedBehavior ModuleTag_MapOverride03
      StartsActive                    = Yes
      ReactionWeaponDamaged           = EruptionOfToxicGooWeaponSmall
      ReactionWeaponReallyDamaged     = EruptionOfToxicGooWeaponSmall
      ContinuousWeaponDamaged         = SmallPoisonFieldWeapon
      ContinuousWeaponReallyDamaged   = SmallPoisonFieldWeapon
      DamageTypes                     = ALL
      DamageAmount                    = 1  ; if damage is >= this value, fire the weapon
    End
  End

End

;RocketBuggyWeapon
;PaladinPointDefenseLaser
;ToxinShellWeapon

WaterTransparency
  TransparentWaterMinOpacity = 1.0   ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 3.0       ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
End




Object CINEExplBox
  ; remove the default die
  RemoveModule ModuleTag_DIE
  AddModule  
    Behavior = InstantDeathBehavior ModuleTag_05
      FX = FX_HumveeExplosionOneFinal
    End
  End
End







 

